version: '3.7'

services:
  server:
    image: zabbix/zabbix-server-mysql:latest
    container_name: zabbix-server
    environment:
      TZ: Asia/Shanghai
      DB_SERVER_HOST: $DB_SERVER_HOST
      DB_SERVER_PORT: $DB_SERVER_PORT
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      # - ./zabbix/zabbix_server.conf:/etc/zabbix/zabbix_server.conf   # 配置优化
    ports:
     - "10051:10051"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    networks:
      default:
        aliases:
          - server
        ipv4_address: 171.50.0.2
    restart: always
   
  web:
    image: zabbix/zabbix-web-nginx-mysql:latest
    container_name: zabbix-web
    environment:
      TZ: Asia/Shanghai
      DB_SERVER_HOST: $DB_SERVER_HOST
      DB_SERVER_PORT: $DB_SERVER_PORT
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      ZBX_SERVER_HOST: $ZBX_SERVER_HOST
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      - ./zabbix/simhei.ttf:/usr/share/zabbix/assets/fonts/DejaVuSans.ttf 
    ports:
      - "10052:80"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    networks:
      default:
        aliases:
          - web
    restart: always 

  db:
    image: mysql:5.7
    container_name: zabbix-mysql
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
     - "10053:3306"
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      - ./zabbix/mysql:/var/lib/mysql
    networks:
      default:
        aliases:
          - db
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 200M
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
     TZ: Asia/Shanghai
    ports:
      - 3000:3000
    volumes:
      - ./grafana/plugins:/var/lib/grafana/plugins
      - ./grafana/grafana.db:/var/lib/grafana/grafana.db
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    restart: always
networks:
    default:
      external:
        name: zabbix